name: Alchemy
favicon: null
layout_spectrum: 0.0441513208206743
typography_spectrum: 0.8801465353462845
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#17BEBB'
    - '#2E282A'
    - '#CD5334'
    - '#EDB88B'
    - '#FAD8D6'
  brandStrength: 0.8509383520577103
  lightness: 0.4151807492598891
  saturation: 0.755474705947563
  rhythmicContrast: 0.6847050953656435
purpose: []
